---

- name: Install pulseaudio
  pacman:
    name: "{{ pulseaudio_default_packages }}"
    state: latest
    update_cache: yes
  become: yes

- name: Install bluetoth support
  pacman:
    name: 
    - bluez
    - bluez-utils
    state: latest
    update_cache: yes
  become: yes


